  AWS_SECRET_ACCESS_KEY: 'sk_test_51JKQJgKZmf28OdEIXqpvisOhoisKsxpmYXtEtAMGcojdQv1FNQFPtvOPSdxX3EavnV0cBDAmJ9n27V0DJDRQvDkI00Yf7l1QVz'
  AWS_ACCESS_KEY_ID: 'pk_test_51JKQJgKZmf28OdEIOkh0Vlt2ftSQfN5XRhnXovJMbDHK4y9ONxyIDeE31uGh5rdnTLcdHHRwHEExkMpVdZjxTLaD00ucCi0hDb'

